# Generated by Django 3.2 on 2021-04-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tbusers',
            fields=[
                ('uid', models.IntegerField(db_column='UID', primary_key=True, serialize=False)),
                ('fname', models.CharField(db_column='FName', max_length=50)),
                ('email', models.CharField(db_column='Email', max_length=30)),
                ('password', models.CharField(db_column='Password', max_length=30)),
                ('level', models.IntegerField(db_column='Level')),
                ('foto', models.TextField(db_column='Foto')),
                ('typetalents', models.CharField(db_column='TypeTalents', max_length=50)),
                ('detailtalents', models.TextField(db_column='DetailTalents')),
                ('district', models.CharField(db_column='District', max_length=30)),
                ('region', models.CharField(db_column='Region', max_length=30)),
                ('contactnumber', models.IntegerField(db_column='ContactNumber')),
                ('ktp', models.TextField(db_column='KTP')),
                ('videolinks', models.TextField(blank=True, db_column='Videolinks', null=True)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'tbusers',
                'managed': False,
            },
        ),
    ]
